import React from "react";
import { FormattedMessage } from "react-intl";

export const TxtData = [
  {
    title: (
      <FormattedMessage
        id="PrivacyPolicy.section_1.title"
        defaultMessage=" Privacy Policy Google Analytics, Twitter Privacy Policy"
      />
    ),
    txt1: (
      <FormattedMessage
        id="PrivacyPolicy.section_1.desc1"
        defaultMessage="Our website uses social plugins (“plugins”) provided by the social network facebook (Facebook Inc., 1601 Willow Road, Menlo Park, 
					California, 94025, USA). The plugins are identifiable by the Facebook logo or the “Like” button on our site. For a full list of all Facebook 
					plugins go to: http://developers.facebook.com/docs/plugins/.
					"
      />
    ),
    txt2: (
      <FormattedMessage
        id="PrivacyPolicy.section_1.desc2"
        defaultMessage="When you visit one of our pages the plugin establishes a direct connection between your browser and the Facebook server. Thus, Facebook 
				receives the information that you (your IP address) visited our website. If you click the Facebook “Like” button while logged in to your 
				facebook account you can link content from our pages to your Facebook profile. This enables Facebook to associate your visit to our pages 
				with your user account. Please note that we as provider of the pages have no knowledge as to the contents of the submitted data or its use 
				by Facebook. For further information please see Facebook’s privacy policy at http://de-de.facebook.com/policy.php.
				"
      />
    ),
    txt3: (
      <FormattedMessage
        id="PrivacyPolicy.section_1.desc3"
        defaultMessage="If you do not want Facebook to associate the data concerning your visit to our website with your member data, please log off Facebook 
				before entering our website."
      />
    ),
  },
  {
    title: (
      <FormattedMessage
        id="PrivacyPolicy.section_2.title"
        defaultMessage="Data policy for the use of Google Analytics"
      />
    ),
    txt1: (
      <FormattedMessage
        id="PrivacyPolicy.section_2.desc1"
        defaultMessage="This website uses Google Analytics, a web analysis service of Google Inc. (“Google”). Google Analytics uses so called “cookies,” text files stored 
				on your computer, to facilitate analysis of your website usage. Information generated by the cookie about your use of this website is usually 
				transmitted to and stored on a Google server in the United States. However, prior to that, when IP anonymisation is activated on this website, 
				your IP address will be truncated by Google (within member states of the European Union or in other states that are party to the agreement on 
				the European Economic Area).
				"
      />
    ),
    txt2: (
      <FormattedMessage
        id="PrivacyPolicy.section_2.desc2"
        defaultMessage="Only in exceptional cases a full IP address will be transmitted to a Google server in the United States and truncated there. On behalf this 
				website’s operator, Google will use this information to evaluate your use of the website, compile reports about website activities, and provide the 
				website’s operator with further services related to website activity and Internet usage. The IP address sent from your browser as part of Google 
				Analytics will not be brought in association with other data held by Google.
				"
      />
    ),
    txt3: (
      <FormattedMessage
        id="PrivacyPolicy.section_2.desc3"
        defaultMessage="You can prevent storage of cookies by adjusting your browser software. In this case, however, please note that you might not be able to fully use 
				all features offered by this website. In addition, you can prevent data generated by the cookie and relating to your use of the website (including 
				your IP address) from being collected and processed by Google by downloading and installing a browser plugin available via this link http://
				tools.google.com/dlpage/gaoptout?hl=de."
      />
    ),
  },
  {
    title: (
      <FormattedMessage
        id="PrivacyPolicy.section_3.title"
        defaultMessage="Privacy policy for the use of Intercom"
      />
    ),
    txt1: (
      <FormattedMessage
        id="PrivacyPolicy.section_3.desc1"
        defaultMessage="Use of Intercom Services: We use third-party analytics services to help understand your usage of our services. In particular, we provide a limited amount of your information (such as sign-up date and some personal information like your email address) to Intercom, Inc. (“Intercom”) and utilize Intercom to collect data for analytics purposes when you visit our website or use our product. As a data processor acting on our behalf, Intercom analyzes your use of our website and/or product and tracks our relationship by way of cookies and similar technologies so that we can improve our service to you. For more information on Intercom's use of cookies, please visit https://www.intercom.com/terms-and-policies#cookie-policy.
				We may also use Intercom as a medium for communications, either through email, or through messages within our product(s). As part of our service agreements, Intercom collects publicly available contact and social information related to you, such as your email address, gender, company, job title, photos, website URLs, social network handles and physical addresses, to enhance your user experience. For more information on the privacy practices of Intercom, please visit https://www.intercom.com/terms-and-policies#privacy. Intercom’s services are governed by Intercom’s terms of use which can be found at https://www.intercom.com/terms-and-policies#terms. If you would like to opt out of having this information collected by or submitted to Intercom, please contact us."
      />
    ),
  },
  {
    title: (
      <FormattedMessage
        id="PrivacyPolicy.section_4.title"
        defaultMessage="Data policy for the use of Hotjar"
      />
    ),
    txt1: (
      <FormattedMessage
        id="PrivacyPolicy.section_4.desc1"
        defaultMessage="We use Hotjar in order to better understand our users’ needs and to optimize this service and experience. Hotjar is a technology service that 
				helps us better understand our users experience (e.g. how much time they spend on which pages, which links they choose to click, what users 
				do and don’t like, etc.) and this enables us to build and maintain our service with user feedback. Hotjar uses cookies and other technologies to 
				collect data on our users’ behavior and their devices (in particular device's IP address (captured and stored only in anonymized form), device 
				screen size, device type (unique device identifiers), browser information, geographic location (country only), preferred language used to display 
				our website). Hotjar stores this information in a pseudonymized user profile. Neither Hotjar nor we will ever use this information to identify 
				individual users or to match it with further data on an individual user. For further details, please see Hotjar’s privacy policy by clicking on this link
				You can opt-out to the creation of a user profile, Hotjar’s storing of data about your usage of our site and Hotjar’s use of tracking cookies on 
				other websites by following this opt-out link."
      />
    ),
  },
];
